ALTER TABLE ACCESOS DROP CONSTRAINT FK_ACCESOS_ID_ACCESO_PADRE
ALTER TABLE GRUPO_ACCESOS DROP CONSTRAINT FK_GRUPO_ACCESOS_ID_GRUPO
ALTER TABLE GRUPO_ACCESOS DROP CONSTRAINT FK_GRUPO_ACCESOS_ID_ACCESO
ALTER TABLE PERFIL_ACCESOS DROP CONSTRAINT FK_PERFIL_ACCESOS_ID_PERFIL
ALTER TABLE PERFIL_ACCESOS DROP CONSTRAINT FK_PERFIL_ACCESOS_ID_ACCESO
ALTER TABLE GRUPOS DROP CONSTRAINT CNN_UN_GRUPOS_NOMBRE
ALTER TABLE PERFILES DROP CONSTRAINT FK_PERFILES_ID_GRUPO
ALTER TABLE USUARIOS DROP CONSTRAINT FK_USUARIOS_ID_PERFIL
ALTER TABLE USUARIOS DROP CONSTRAINT FK_USUARIOS_ID_PERSONA
ALTER TABLE USUARIOS DROP CONSTRAINT CNN_UN_USARIO_NOMBRE
ALTER TABLE CHEQUERAS DROP CONSTRAINT FK_CHEQUERAS_ID_CUENTA
ALTER TABLE CUENTAS DROP CONSTRAINT FK_CUENTAS_MONEDA
ALTER TABLE CUENTAS DROP CONSTRAINT FK_CUENTAS_ID_BANCO
ALTER TABLE PERFIL_ACCIONES DROP CONSTRAINT FK_PERFIL_ACCIONES_PERFIL_ID
DROP TABLE ACCESOS
DROP INDEX IDX_GRUPO_ACCESOS
DROP TABLE GRUPO_ACCESOS
DROP TABLE PERFIL_ACCESOS
DROP INDEX IDX_GRUPOS_NOMBRE
DROP TABLE GRUPOS
DROP TABLE PERFILES
DROP TABLE USUARIOS
DROP TABLE CATG_MONEDAS
DROP TABLE CATG_DOCUMENTOS
DROP TABLE INFO_PERSONAS
DROP TABLE BANCOS
DROP TABLE CHEQUERAS
DROP TABLE CUENTAS
DROP TABLE PERFIL_ACCIONES
DROP SEQUENCE seq_banco_id
DROP SEQUENCE SEQ_ACCESO_ID
DROP SEQUENCE seq_catg_monedas
DROP SEQUENCE SEQ_PERFIL_ID
DROP SEQUENCE SEQ_PRF_ACC_ID
DROP SEQUENCE seq_catg_documentos
DROP SEQUENCE SEQ_GRUPO_ID
DROP SEQUENCE SEQ_CUENTA_ID
DROP SEQUENCE SEQ_PERSONA_ID
DROP SEQUENCE SEQ_CHEQUERA_ID
DROP SEQUENCE SEQ_GRP_ACC_ID
DROP SEQUENCE SEQ_USUARIOS_ID
