/*
      ACCESOS
*/
CREATE TABLE ACCESOS(
      ID_ACCESO               NUMBER(19)                          NOT NULL,
      ID_ACCESO_PADRE         NUMBER(19),
      ES_PADRE                NUMBER(1)         DEFAULT 0         NOT NULL,
      ESTADO                  NUMBER(1)         DEFAULT 0         NOT NULL,
      TITULO                  VARCHAR2(25)                        NOT NULL,
      URL                     VARCHAR2(255),
      REDIRECCIONAMIENTO      NUMBER(1)         DEFAULT 0         NOT NULL,
      REG_CREACION            TIMESTAMP         DEFAULT SYSDATE   NOT NULL,
      REG_ULT_MODIFICACION    TIMESTAMP,
      VERSION                 NUMBER(19),
      PRIMARY KEY (ID_ACCESO)
);

ALTER TABLE ACCESOS 
    ADD CONSTRAINT FK_TBL_ACC_ID_ACC_PADRE 
    FOREIGN KEY (ID_ACCESO_PADRE)
    REFERENCES ACCESOS (ID_ACCESO);
   
ALTER TABLE ACCESOS 
    ADD CONSTRAINT CK_TBL_ACC_VALORES 
    CHECK ((ES_PADRE BETWEEN 0 AND 1) and (ESTADO BETWEEN 0 AND 1) AND (REDIRECCIONAMIENTO BETWEEN 0 AND 1));
    
CREATE SEQUENCE SEQ_ACCESO_ID 
      START WITH 20
      INCREMENT BY 1;
      
/*
    GRUPOS
*/      
CREATE TABLE GRUPOS(
      ID_GRUPO                NUMBER(19)                          NOT NULL,
      NOMBRE                  VARCHAR2(50)                        NOT NULL,
      DESCRIPCION             CLOB              DEFAULT EMPTY_CLOB()  NOT NULL,
      REG_CREACION            TIMESTAMP         DEFAULT SYSDATE   NOT NULL,
      REG_ULT_MODIFICACION    TIMESTAMP,
      VERSION                 NUMBER(19),
      PRIMARY KEY (ID_GRUPO)
);

ALTER TABLE GRUPOS 
    ADD CONSTRAINT CNN_UN_GRUPOS_NOMBRE 
    UNIQUE (NOMBRE);    

  
CREATE SEQUENCE SEQ_GRUPO_ID
      START WITH 20
      INCREMENT BY 1;

/*
    GRUPOS ACCESOS
*/
      
CREATE TABLE GRUPO_ACCESOS (
      ID_GRP_ACC              NUMBER(19)                          NOT NULL, 
      ID_ACCESO               NUMBER(19)                          NOT NULL, 
      ID_GRUPO                NUMBER(19)                          NOT NULL, 
      REG_CREACION            TIMESTAMP         DEFAULT SYSDATE   NOT NULL,
      REG_ULT_MODIFICACION    TIMESTAMP,
      VERSION                 NUMBER(19),
      PRIMARY KEY (ID_GRP_ACC)
);

ALTER TABLE GRUPO_ACCESOS 
    ADD CONSTRAINT FK_GRUPO_ACCESOS_GRUPO 
    FOREIGN KEY (ID_GRUPO) 
    REFERENCES GRUPOS (ID_GRUPO);
    
ALTER TABLE GRUPO_ACCESOS 
    ADD CONSTRAINT FK_GRUPO_ACCESOS_ACCESO 
    FOREIGN KEY (ID_ACCESO) 
    REFERENCES ACCESOS (ID_ACCESO);

CREATE INDEX IDX_GRUPO_ACCESOS 
    ON GRUPO_ACCESOS (ID_GRUPO, ID_ACCESO);
    
CREATE SEQUENCE SEQ_GRP_ACC_ID 
    START WITH 20
    INCREMENT BY 1;

/*
    PERFILES
*/
CREATE TABLE PERFILES(
      ID_PERFIL               NUMBER(19)                          NOT NULL,
      ID_GRUPO                NUMBER(19)                          NOT NULL, 
      NOMBRE                  VARCHAR2(50)                        NOT NULL,
      ESTADO				  NUMBER(1,0)		DEFAULT 0		  NOT NULL,
      REG_CREACION            TIMESTAMP         DEFAULT SYSDATE   NOT NULL,
      REG_ULT_MODIFICACION    TIMESTAMP,
      VERSION                 NUMBER(19),
      PRIMARY KEY (ID_PERFIL)
);

ALTER TABLE PERFILES 
    ADD CONSTRAINT CK_TBL_PRF_ESTADO 
    CHECK (ESTADO BETWEEN 0 AND 1);

ALTER TABLE PERFILES 
    ADD CONSTRAINT FK_PERFILES_ID_GRUPO 
    FOREIGN KEY (ID_GRUPO) 
    REFERENCES GRUPOS (ID_GRUPO);
    
CREATE SEQUENCE SEQ_PERFIL_ID 
    START WITH 20
    INCREMENT BY 1; 

/*
    PERFIL ACCESOS
*/

CREATE TABLE PERFIL_ACCESOS (
      ID_PRF_ACC              NUMBER(19)                          NOT NULL, 
      ID_ACCESO               NUMBER(19)                          NOT NULL, 
      ID_PERFIL               NUMBER(19)                          NOT NULL, 
      REG_CREACION            TIMESTAMP         DEFAULT SYSDATE   NOT NULL,
      REG_ULT_MODIFICACION    TIMESTAMP,
      VERSION                 NUMBER(19),      PRIMARY KEY (ID_PRF_ACC)
);

ALTER TABLE PERFIL_ACCESOS 
    ADD CONSTRAINT FK_PERFIL_ACCESOS_PERFIL 
    FOREIGN KEY (ID_PERFIL) 
    REFERENCES PERFILES (ID_PERFIL);
    
ALTER TABLE PERFIL_ACCESOS 
    ADD CONSTRAINT FK_PERFIL_ACCESOS_ACCESO 
    FOREIGN KEY (ID_ACCESO) 
    REFERENCES ACCESOS (ID_ACCESO);
  
CREATE SEQUENCE SEQ_PRF_ACC_ID 
    START WITH 20
    INCREMENT BY 1;
    
/*
    ACCESOS ACCIONES    
 */
 
CREATE TABLE PERFIL_ACCIONES (
      PERFIL_ID               NUMBER(19)                          NOT NULL, 
      ACCION                  VARCHAR2(20)                       NOT NULL
);

ALTER TABLE PERFIL_ACCIONES 
    ADD CONSTRAINT FK_PERFIL_ACCIONES_PERFIL 
    FOREIGN KEY (PERFIL_ID) REFERENCES PERFIL_ACCESOS (ID_PRF_ACC);

/*
 * PERSONAS (nota: tomar en cuenta que la tabla usuarios ya debe de existir al momento de crear la relacion con dicha tabla)
 */
    
CREATE TABLE INFO_PERSONAS (
		ID_PERSONA 				NUMBER(19) 						NOT NULL,  
		FECHA_NACIMIENTO 		DATE 							NULL, 
		PRIMER_NOMBRE 			VARCHAR2(25) 					NOT NULL, 
		SEGUNDO_NOMBRE 			VARCHAR2(25) 					NULL, 
		TERCER_NOMBRE 			VARCHAR2(25) 					NULL, 
		PRIMER_APELLIDO 		VARCHAR2(25) 					NULL, 
		SEGUNDO_APELLIDO 		VARCHAR2(25) 					NULL, 
		TYPE_ 					VARCHAR2(31) 					NULL, 
		REG_CREACION 			TIMESTAMP 						NULL, 
		REG_ULT_MODIFICACION 	TIMESTAMP 						NULL, 
		VERSION 				NUMBER(19) 						NULL, 
		PRIMARY KEY (ID_PERSONA));
		
CREATE SEQUENCE SEQ_PERSONA_ID 
	START WITH 20
	INCREMENT BY 1;
    
    
/*
  USUARIOS
*/
CREATE TABLE USUARIOS (
      ID_USUARIO              NUMBER(19)                          NOT NULL, 
      ID_PERFIL               NUMBER(19)                          NOT NULL, 
      ID_PERSONA 			  NUMBER(19) 						  NULL,
      USUARIO                 VARCHAR2(255)                       NOT NULL, 
      CONTRASENA              VARCHAR2(255)                       NOT NULL, 
      ESTADO                  VARCHAR2(255)                       NOT NULL, 
      REG_CREACION            TIMESTAMP         DEFAULT SYSDATE   NOT NULL,
      REG_ULT_MODIFICACION    TIMESTAMP,
      VERSION                 NUMBER(19),
      PRIMARY KEY (ID_USUARIO)
);

ALTER TABLE USUARIOS 
    ADD CONSTRAINT CNN_UN_USARIO_NOMBRE 
    UNIQUE (USUARIO);

ALTER TABLE USUARIOS 
    ADD CONSTRAINT FK_USUARIOS_ID_PERFIL 
    FOREIGN KEY (ID_PERFIL) 
    REFERENCES PERFILES (ID_PERFIL);
    
ALTER TABLE USUARIOS 
	ADD CONSTRAINT FK_USUARIOS_ID_PERSONA 
	FOREIGN KEY (ID_PERSONA) 
	REFERENCES INFO_PERSONAS (ID_PERSONA);
    
CREATE SEQUENCE SEQ_USUARIOS_ID 
    START WITH 20
    INCREMENT BY 1;
    
/*
 * Catalogo de monedas
 */
    
    
CREATE TABLE CATG_MONEDAS (
		ID_MONEDA 				NUMBER(19) 						NOT NULL, 
		ABREVIATURA 			VARCHAR2(255) 					NULL, 
		MONEDA 					VARCHAR2(255) 					NOT NULL, 
		SIMBOLO 				VARCHAR2(255) 					NULL, 
		ESTADO					NUMBER(1)		DEFAULT 0		NOT NULL,
		REG_CREACION 			TIMESTAMP 						NULL, 
		REG_ULT_MODIFICACION 	TIMESTAMP 						NULL, 
		VERSION 				NUMBER(19) 						NULL, 
		PRIMARY KEY (ID_MONEDA));
		
		
ALTER TABLE CATG_MONEDAS 
    ADD CONSTRAINT CK_TBL_MDN_ESTADO 
    CHECK (ESTADO BETWEEN 0 AND 1);
		
CREATE SEQUENCE seq_catg_monedas 
	START WITH 20
	INCREMENT by 1;
	
    
    
/*
 * Catalogo de Documentos
 * 
 */
    
CREATE TABLE CATG_DOCUMENTOS (
		ID_DOCUMENTO 			NUMBER(19) 						NOT NULL, 
		NOMBRE 					VARCHAR2(25) 					NOT NULL, 
		DESCRIPCION 			CLOB 							NULL, 
		FORMATO 				VARCHAR2(50) 					NULL, 
		ESTADO 					NUMBER(1) 		DEFAULT 0 		NULL, 
		REG_CREACION 			TIMESTAMP 						NULL, 
		REG_ULT_MODIFICACION 	TIMESTAMP 						NULL, 
		VERSION 				NUMBER(19) 						NULL, 
		PRIMARY KEY (ID_DOCUMENTO));	
		
ALTER TABLE CATG_DOCUMENTOS 
    ADD CONSTRAINT CK_TBL_DCM_ESTADO 
    CHECK (ESTADO BETWEEN 0 AND 1);
		
CREATE SEQUENCE seq_catg_documentos  
	START WITH 20
	INCREMENT by 1;
	
/*
 * 	BANCOS
 */
	
CREATE TABLE BANCOS (
		ID_BANCO 				NUMBER(19) 							NOT NULL, 
		ESTADO 					NUMBER(1) 		DEFAULT 0 			NULL, 
		NOMBRE 					VARCHAR2(50) 						NOT NULL, 
		PAGINA_WEB 				VARCHAR2(50) 						NULL, 
		VERSION 				NUMBER(19) 							NULL, 
		REG_CREACION            TIMESTAMP		DEFAULT SYSDATE   	NOT NULL,
		REG_ULT_MODIFICACION    TIMESTAMP, 
		PRIMARY KEY (ID_BANCO));
		
CREATE SEQUENCE SEQ_BANCO_ID 
	START WITH 20
	INCREMENT BY 1;
	
/*
 *	CUENTAS 
 */
	
CREATE TABLE CUENTAS (
		ID_CUENTA 				NUMBER(19) 							NOT NULL, 
		ID_BANCO 				NUMBER(19) 							NOT NULL, 
		CUENTA_NO 				VARCHAR2(255) 						NULL,
		MONEDA 					NUMBER(19) 							NOT NULL, 
		SALDO 					NUMBER(18,2) 	DEFAULT 0.00		NOT NULL, 
		TIPO 					VARCHAR2(255) 						NULL, 
		ESTADO 					NUMBER(1) 		DEFAULT 0 			NULL, 
		FECHA_APERTURA 			TIMESTAMP 							NULL, 
		REG_CREACION            TIMESTAMP		DEFAULT SYSDATE   	NOT NULL,
		REG_ULT_MODIFICACION    TIMESTAMP, 
		VERSION 				NUMBER(19) NULL, 		
		PRIMARY KEY (ID_CUENTA));

ALTER TABLE CUENTAS 
	ADD CONSTRAINT FK_CUENTAS_MONEDA 
	FOREIGN KEY (MONEDA) 
	REFERENCES CATG_MONEDAS (ID_MONEDA);

ALTER TABLE CUENTAS 
	ADD CONSTRAINT FK_CUENTAS_ID_BANCO 
	FOREIGN KEY (ID_BANCO) 
	REFERENCES BANCOS (ID_BANCO);
	
CREATE SEQUENCE SEQ_CUENTA_ID 
	START WITH 20
	INCREMENT BY 1;
	
/*
 *	CHEQUERA 
 */
	
CREATE TABLE CHEQUERAS (
		ID_CHEQUERA 			NUMBER(19) 							NOT NULL, 
		ID_CUENTA 				NUMBER(19) 							NOT NULL, 
		CODIGO 					VARCHAR2(50) 						NOT NULL, 
		ESTADO 					VARCHAR2(20) 	DEFAULT 'Activo'	NOT NULL, 
		FECHA_AUTORIZACION 		DATE 								NOT NULL, 
		FECHA_BAJA 				DATE 								NULL, 
		NUMERACION_FINAL 		NUMBER(19) 							NOT NULL, 
		NUMERACION_INICIAL 		NUMBER(19) 							NOT NULL, 
		TOTAL_CHEQUES 			NUMBER(10) 							NOT NULL, 
		REG_CREACION            TIMESTAMP		DEFAULT SYSDATE   	NOT NULL,
		REG_ULT_MODIFICACION    TIMESTAMP, 
		VERSION 				NUMBER(19) 							NULL, 
		PRIMARY KEY (ID_CHEQUERA));

ALTER TABLE CHEQUERAS 
	ADD CONSTRAINT FK_CHEQUERAS_ID_CUENTA 
	FOREIGN KEY (ID_CUENTA) 
	REFERENCES CUENTAS (ID_CUENTA);

CREATE SEQUENCE SEQ_CHEQUERA_ID 
	START WITH 20
	INCREMENT BY 1;
	

	
/*
 * 		TRANSACCIONES
 * */	
CREATE TABLE TRANSACCIONES (
		NO_TRANSACCION 			NUMBER(19) 							NOT NULL, 
		NO_DOCUMENTO 			VARCHAR2(75) 						NULL, 
		FECHA_SOLICITUD 		TIMESTAMP 							NULL, 
		FUENTE 					VARCHAR2(75) 						NULL, 
		ID_CUENTA 				NUMBER(19) 							NULL, 
		MONTO 					NUMBER(18,2) 						NOT NULL, 
		TIPO 					VARCHAR2(20) 						NOT NULL, 
	PRIMARY KEY (NO_TRANSACCION));



CREATE SEQUENCE SEQ_TRANSACCIONES 
	START WITH 1
	INCREMENT BY 1;


/*
 * 		DEBITOS
 * */	
CREATE TABLE DEBITOS (
		ID                 		NUMBER(19)              			NOT NULL,		
		NO_TRANSACCION 			NUMBER(19) 							NOT NULL, 
		CUENTA_NO 				NUMBER(19) 							NOT NULL, 
		NO_DOCUMENTO 			VARCHAR2(255) 						NOT NULL, 
		MONTO 					NUMBER(18,2) 						NULL, 
		SOLICITUD 				TIMESTAMP 							NOT NULL, 
		EJECUCION 				TIMESTAMP	 	DEFAULT SYSDATE		NULL, 
		ESTADO 					NUMBER(1)		DEFAULT 0 			NOT NULL, 
		MENSAJE 				VARCHAR2(255) 						NULL, 
		FUENTE 					VARCHAR2(75) 						NULL, 
	PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_DEBITOS 
	START WITH 1
	INCREMENT BY 1;	
	
ALTER TABLE DEBITOS 
    ADD CONSTRAINT CK_DEBITOS_ESTADO
    CHECK (ESTADO BETWEEN 0 AND 1);
    
ALTER TABLE DEBITOS 
    ADD CONSTRAINT CNN_UN_TRANSACCION_DB
    UNIQUE (NO_TRANSACCION);
  
/*
 * 		CREDITOS
 * */	
CREATE TABLE CREDITOS (
		ID                 		NUMBER(19)              			NOT NULL,
		NO_TRANSACCION 			NUMBER(19) 							NOT NULL, 
		CUENTA_NO 				NUMBER(19) 							NOT NULL, 
		NO_DOCUMENTO 			VARCHAR2(255) 						NOT NULL, 
		MONTO 					NUMBER(18,2) 						NULL, 
		SOLICITUD 				TIMESTAMP 							NOT NULL, 
		EJECUCION 				TIMESTAMP	 	DEFAULT SYSDATE		NULL, 
		ESTADO 					NUMBER(1)		DEFAULT 0 			NOT NULL, 
		MENSAJE 				VARCHAR2(255) 						NULL, 
		FUENTE 					VARCHAR2(75) 						NULL, 
	PRIMARY KEY (ID));
	
CREATE SEQUENCE SEQ_CREDITOS 
	START WITH 1
	INCREMENT BY 1;
	
ALTER TABLE CREDITOS 
    ADD CONSTRAINT CK_CREDITOS_ESTADO
    CHECK (ESTADO BETWEEN 0 AND 1);
    
 ALTER TABLE CREDITOS 
    ADD CONSTRAINT CNN_UN_TRANSACCION_CR
    UNIQUE (NO_TRANSACCION);
	