CREATE TABLE COMPRAS_PROVEEDORES_HISTORY (
	ID_COMPRA 		NUMBER(19) 							NOT NULL, 
	ID_PROVEEDOR 	NUMBER(19) 							NOT NULL,
	FECHA_COMPRA 	TIMESTAMP 		DEFAULT SYSDATE		NOT NULL, 
	ESTADO 			VARCHAR2(25) 						NOT NULL, 
	MONTO 			NUMBER(18,2) 						NULL, 
	SALDO 			NUMBER(18,2) 						NULL, 
	ADDED_BY 		NUMBER(19) 							NULL, 
	UPDATED_BY 		NUMBER(19) 							NULL, 
	ADD_DATE 		TIMESTAMP 		DEFAULT SYSDATE		NOT NULL, 
	UPDATE_DATE 	TIMESTAMP 							NULL, 
	VERSION 		NUMBER(19) 							NULL, 
	START_DATE 		TIMESTAMP 							NULL, 
	END_DATE 		TIMESTAMP 							NULL
	);
	
	
CREATE TABLE  CHEQUES_HISTORY(
	ID_CHEQUE 		NUMBER(19) 							NOT NULL, 
	ID_CHEQUERA 	NUMBER(19) 							NOT NULL, 
	NO_CHEQUE		NUMBER(20) 							NULL, 
	MONTO 			NUMBER(18,2) 						NULL, 
	SOBRE_SALDO 	NUMBER(1) 		DEFAULT 0 			NULL, 
	ID_COMPRA 		NUMBER(19)	 						NULL, 
	FECHA_EMISION 	TIMESTAMP 							NULL, 
	FECHA_EJECUCION	TIMESTAMP 							NULL, 
	ESTADO 			VARCHAR2(25) 						NOT NULL, 
	ADDED_BY 		NUMBER(19) 							NULL, 
	UPDATED_BY 		NUMBER(19)  						NULL, 
	ADD_DATE 		TIMESTAMP 		DEFAULT SYSDATE		NOT NULL, 
	UPDATE_DATE 	TIMESTAMP 							NULL, 
	VERSION 		NUMBER(19) 							NULL,
	START_DATE 		TIMESTAMP 							NULL, 
	END_DATE 		TIMESTAMP 							NULL
	);
	
	
CREATE TABLE CHEQUERAS_HISTORY (
	ID_CHEQUERA 			NUMBER(19) 							NOT NULL, 
	ID_CUENTA 				NUMBER(19) 							NOT NULL, 
	NUMERO					VARCHAR2(20)						NOT NULL,
	ESTADO 					VARCHAR2(20) 	DEFAULT 'NUEVA'		NOT NULL,  
	FECHA_AUTORIZACION 		DATE 								NOT NULL, 
	FECHA_BAJA 				DATE 								NULL, 
	NUMERACION_FINAL 		NUMBER(19) 							NOT NULL, 
	NUMERACION_INICIAL 		NUMBER(19) 							NOT NULL, 
	TOTAL_CHEQUES 			NUMBER(10) 							NOT NULL, 
	ADDED_BY 				NUMBER(19) 							NULL, 
	UPDATED_BY 				NUMBER(19) 							NULL, 
	ADD_DATE           	 	TIMESTAMP		DEFAULT SYSDATE   	NOT NULL,
	UPDATE_DATE    			TIMESTAMP							NULL, 
	VERSION 				NUMBER(19) 							NULL, 
    START_DATE 		        TIMESTAMP 							NULL, 
    END_DATE 		        TIMESTAMP 							NULL
    );

 ALTER TABLE CHEQUERAS_HISTORY ADD (CHEQUES_EMITIDOS NUMBER(20) DEFAULT 0);
 
    
