INSERT 	INTO GRUPOS (ID_GRUPO, NOMBRE, DESCRIPCION, REG_CREACION, VERSION) 
		VALUES (SEQ_GRUPO_ID.NEXTVAL, 'ADMINISTRADOR', 'ADMINISTRADOR DEL SISTEMA', SYSDATE, 1);
		
		
INSERT INTO PERFILES (ID_PERFIL, ID_GRUPO, NOMBRE, ESTADO,REG_CREACION, VERSION)
    VALUES (SEQ_PERFIL_ID.NEXTVAL, 20, 'ADMIN A',1,SYSDATE, 1);

    
INSERT INTO USUARIOS (ID_USUARIO,ID_PERFIL,USUARIO,CONTRASENA,ESTADO,REG_CREACION,VERSION) 
	VALUES (SEQ_USUARIOS_ID.NEXTVAL,20,'ADMIN','73acd9a5972130b75066c82595a1fae3','Activo',SYSDATE,1);
	
	
	
Insert 	into ACCESOS (ID_ACCESO,ID_ACCESO_PADRE,ES_PADRE,ESTADO,TITULO,URL,REDIRECCIONAMIENTO,REG_CREACION,VERSION) 
        values (SEQ_ACCESO_ID.NEXTVAL,null,1,1,'Seguridad','seguridad/admin',1,sysdate,1);

Insert into ACCESOS (ID_ACCESO,ID_ACCESO_PADRE,ES_PADRE,ESTADO,TITULO,URL,REDIRECCIONAMIENTO,REG_CREACION,VERSION) 
        values (SEQ_ACCESO_ID.NEXTVAL,null,1,1,'Bancos','bancos/banca',1,sysdate,1);


Insert  into ACCESOS (ID_ACCESO,ID_ACCESO_PADRE,ES_PADRE,ESTADO,TITULO,URL,REDIRECCIONAMIENTO,REG_CREACION,VERSION) 
        values (SEQ_ACCESO_ID.NEXTVAL,null,1,1,'Catalogos','catalogos/catalogos',1,sysdate,1);

Insert  into ACCESOS (ID_ACCESO,ID_ACCESO_PADRE,ES_PADRE,ESTADO,TITULO,URL,REDIRECCIONAMIENTO,REG_CREACION,VERSION) 
        values (SEQ_ACCESO_ID.NEXTVAL,null,1,1,'Configuraciones','configuraciones/configuraciones',1,sysdate,1);