/*
    ACCESOS
*/

ALTER TABLE ACCESOS DROP CONSTRAINT FK_TBL_ACC_ID_ACC_PADRE ;
ALTER TABLE ACCESOS DROP CONSTRAINT CK_TBL_ACC_VALORES;
 
DROP SEQUENCE SEQ_ACCESO_ID;

DROP TABLE ACCESOS CASCADE CONSTRAINT;

/*
    GRUPOS
*/ 

ALTER TABLE GRUPOS DROP CONSTRAINT CNN_UN_GRUPOS_NOMBRE;    
DROP SEQUENCE SEQ_GRUPO_ID;

DROP TABLE GRUPOS CASCADE CONSTRAINT;

/*
  GRUPOS ACCESOS
*/
ALTER TABLE GRUPO_ACCESOS DROP CONSTRAINT FK_GRUPO_ACCESOS_GRUPO;
ALTER TABLE GRUPO_ACCESOS DROP CONSTRAINT FK_GRUPO_ACCESOS_ACCESO ;
DROP INDEX IDX_GRUPO_ACCESOS;
DROP SEQUENCE SEQ_GRP_ACC_ID;

DROP TABLE GRUPO_ACCESOS CASCADE CONSTRAINT;


/*
    PERFILES
*/
ALTER TABLE PERFILES DROP CONSTRAINT FK_PERFILES_ID_GRUPO ;    
DROP SEQUENCE SEQ_PERFIL_ID ;

DROP TABLE PERFILES CASCADE CONSTRAINT;

/*
    PERFILES ACCESOS
*/
ALTER TABLE PERFIL_ACCESOS DROP CONSTRAINT FK_PERFIL_ACCESOS_PERFIL ;
ALTER TABLE PERFIL_ACCESOS DROP CONSTRAINT FK_PERFIL_ACCESOS_ACCESO;
DROP SEQUENCE SEQ_PRF_ACC_ID ;

DROP TABLE PERFIL_ACCESOS CASCADE CONSTRAINT;

/*
    ACCESOS ACCIONES    
 */
ALTER TABLE PERFIL_ACCIONES DROP CONSTRAINT FK_PERFIL_ACCIONES_PERFIL ;

DROP TABLE PERFIL_ACCIONES CASCADE CONSTRAINT;

/*
 * INFO_PERSONAS (USADA TAMBIEN PARA EMPLEADOS)
 * */

ALTER TABLE INFO_PERSONAS DROP CONSTRAINT FK_INFO_PRS_USR_ID;
DROP SEQUENCE SEQ_PERSONA_ID ;

DROP TABLE INFO_PERSONAS CASCADE CONSTRAINT;


/*
  USUARIOS
*/
ALTER TABLE USUARIOS DROP CONSTRAINT CNN_UN_USARIO_NOMBRE;
ALTER TABLE USUARIOS DROP CONSTRAINT FK_USUARIOS_ID_PERFIL;   
ALTER TABLE USUARIOS DROP CONSTRAINT FK_USUARIOS_ID_PERSONA;
DROP SEQUENCE SEQ_USUARIOS_ID;

DROP TABLE USUARIOS CASCADE CONSTRAINT;

/*
 * Catalogo de monedas
 */
    

ALTER TABLE CATG_MONEDAS DROP CONSTRAINT CK_TBL_MDN_ESTADO;
DROP SEQUENCE seq_catg_monedas;

DROP TABLE CATG_MONEDAS CASCADE CONSTRAINT;

/*
 * Catalogo de Documentos de identificacion
 */

ALTER TABLE CATG_DOCUMENTOS 
    DROP CONSTRAINT CK_TBL_DCM_ESTADO ;
		
DROP SEQUENCE seq_catg_documentos ;

DROP TABLE CATG_DOCUMENTOS CASCADE CONSTRAINT;

/*
 * BANCOS
 */
DROP SEQUENCE SEQ_BANCO_ID;

DROP TABLE BANCOS CASCADE CONSTRAINT;


/*
 * CUENTAS
 */

ALTER TABLE CUENTAS 
	DROP CONSTRAINT FK_CUENTAS_MONEDA;

ALTER TABLE CUENTAS 
	DROP CONSTRAINT FK_CUENTAS_ID_BANCO;

DROP SEQUENCE SEQ_CUENTA_ID;

DROP TABLE CUENTAS CASCADE CONSTRAINT;
	
/*
 * CHEQUERAS
 */
ALTER TABLE CHEQUERAS 
	DROP CONSTRAINT FK_CHEQUERAS_ID_CUENTA;

DROP SEQUENCE SEQ_CHEQUERA_ID;

DROP TABLE CHEQUERAS CASCADE CONSTRAINT;


/*
 *TRANSACCIONES 
 */

DROP SEQUENCE SEQ_TRANSACCIONES;
DROP TABLE TRANSACCIONES CASCADE CONSTRAINT;

/*
 * 	DEBITOS
 * */
DROP SEQUENCE SEQ_DEBITOS;
DROP TABLE DEBITOS;

/*
 * 	CREDITOS
 * */
DROP SEQUENCE SEQ_CREDITOS;
DROP TABLE CREDITOS;


